image: gitpod/workspace-dotnet-vnc
tasks:
  - init: wget https://downloads.tuxfamily.org/godotengine/3.3.4/Godot_v3.3.4-stable_x11.64.zip && unzip Godot_v3.3.4-stable_x11.64.zip
    command: ./Godot_v3.3.4-stable_x11.64