cargo-features = ["edition2021"]
[package]
name = "client-bevy"
version = "0.1.0"
edition = "2021"

[features]
default = [
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png"
]

native = [
    "bevy/bevy_wgpu"
]

web = [
    "bevy_webgl2",
]

dev = [
    "bevy/dynamic",
    "native",
]

[dependencies]
bevy = { version="0.5.0" }
winit = {version = "0.24.0"}
bevy_webgl2 = { version = "0.5.0", optional = true }

[profile.dev]
opt-level = 1

[profile.release]
# lto = true
# opt-level = 's'