name: Build VTT

on:
  push:
    branches: [main]
    
env:
  CARGO_TERM_COLOR: always
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: vtt-client

jobs:
  build-server:
    strategy:
      matrix:
        build: 
          - name: ubuntu
            target: aarch64-unknown-linux-gnu
          - name: windows
            target: x86_64-pc-windows-gnu
          - name: macos-intel
            target: x86_64-apple-darwin
          - name: macos-m1
            target: aarch64-apple-darwin
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - run: rustup default beta
      - run: rustup target add ${{matrix.build.target}}
      - name: Build ${{matrix.build.name}}
        run: cargo build --verbose --release --target ${{matrix.build.target}}
        working-directory: server
      - uses: Swatinem/rust-cache@v1
      - name: Upload Server
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build.name}}-server
          path: target/release/server.*