name: Build VTT

on:
  push:
    branches: [main]
    
env:
  CARGO_TERM_COLOR: always
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: vtt-client

jobs:
  build-rust:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add clang to $PATH
        if: runner.os == 'Windows'
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
      - run: rustup default beta
      - name: Build ${{matrix.os}}
        run: cargo build --verbose --release
      - uses: Swatinem/rust-cache@v1
      - name: Upload Client Lib
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.os}}-client-lib
          path: target/release/client-lib.*
      - name: Upload Server
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.os}}-server
          path: target/release/server.*
  build-godot:
    needs: build-rust
    strategy:
      matrix:
        builds: 
          - libName: ubuntu
            buildName: "Linux/X11"
          - libName: windows
            buildName: "Windows Desktop"
          - libName: macox
            buildName: "Mac OSX"
    
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download Client Lib
        uses: actions/download-arifact@v2
        with:
          name: ${{matrix.builds.libName}}-client-lib
          path: client-godot/
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: ${{matrix.builds.buildName}} Build
        run: |
          mkdir -v -p build/${{matrix.builds.libName}}
          cd $EXPORT_NAME
          godot -v --export "${{matrix.builds.buildName}}" ../build/${{matrix.builds.libName}}/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.builds.libName}}-client
          path: build/${{matrix.builds.libName}}