name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev wget xvfb
      - name: Setup Swiftshader
        run: |
          wget https://github.com/qarmin/gtk_library_store/releases/download/3.24.0/swiftshader.zip;
          unzip swiftshader.zip;
          curr="$(pwd)/libvk_swiftshader.so";
          sed -i "s|PATH_TO_CHANGE|$curr|" vk_swiftshader_icd.json;
      - run: rustup default stable
      - name: Run tests
        run: cargo test --verbose
      - uses: Swatinem/rust-cache@v1

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - run: rustup default stable
      - run: rustup component add rustfmt
      - name: Run format
        run: cargo fmt -- --check
      - uses: Swatinem/rust-cache@v1
        
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - run: rustup default stable
      - run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy
      - uses: Swatinem/rust-cache@v1
