name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Run tests
        run: cargo test --verbose
      - uses: Swatinem/rust-cache@v1

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - run: rustup component add rustfmt
      - name: Run format
        run: cargo fmt -- --check
      - uses: Swatinem/rust-cache@v1
        
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev
      - run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy
      - uses: Swatinem/rust-cache@v1
